# -*- coding: utf-8 -*-
"""Urban vs Rural California

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jO95dagu4r5LyHKZunaQuG9fTEgpMAE9
"""

import pandas as pd
import altair as alt
import streamlit as st

data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

st.set_page_config(page_title="Urban vs Rural California", initial_sidebar_state = 'collapsed', layout='wide')

#Can we scroll? Controls
#Input boxes/Buttons
#What does your layout look like?

#Where is my daata [Github, Streamlit, Browser]
#Sessions as part of interactivity
#streamlit layouts and containers, look it up

with st.container():
  st.image('https://cdn.cookielaw.org/logos/abdd0205-22cc-4fe3-9905-15c572527293/7556293c-5b79-4ada-b220-2a9a79bf5b49/be7ee31a-0ca2-4aeb-894e-ee0219934cbe/okcupid_whitebg.png')

  
col1, col2, col3 = st.columns(3)

data.info()

chart1 = alt.Chart(data).mark_circle(size = 100).encode(
    x = 'Age',
    y = 'Fare',
    tooltip = ['Name', 'Survived']
)

chart2 = alt.Chart(data).mark_area().encode(
    alt.X('Fare'),
    alt.Y('Age')
)
chart3 = alt.Chart(data).mark_tick().encode(
    alt.X('Ticket'),
    alt.Y("Fare")
)

with col1:
  st.altair_chart(chart1, use_container_width = True)
with col2:
    st.altair_chart(chart2, use_container_width = True)
with col3:
  st.header("This is col 3")
  st.altair_chart()
#  pass

data.sample(10)

#Make a sidebar
with st.sidebar:
  st.header("This is a sidebar")
#Make three charts